# run_pipeline.R -------------------------------------------------------------
# CanPAS curation pipeline entry point: runs the steps in order, with pre-flight
# checks, a log and an exit code.
#
# 位置 / location
#   The pipeline ships inside the package as consolidated scripts, one file per
#   step group, under inst/pipeline/ (this directory).  The set is scripts only:
#   no data files are included.  The data root (expression matrices, raw series
#   matrices, processed tables, catalog) is a separate project tree.
#
# 与旧入口的差异 / difference from the original entry point
#   The original pipeline/run_pipeline.R ran one Rscript per step from
#   <project>/pipeline/R/<n>_*.R.  The code is now consolidated, so each step is
#   still run in its own Rscript process (same isolation, same exit-code
#   handling, same log), but the command sources the consolidated file and calls
#   that step's run_*() function.  Step ids, the --list/--check/--from/--to/
#   --only/--dry-run interface and the log format are unchanged.
#
# 用法 / usage:
#   Rscript run_pipeline.R --list                  # list every step
#   Rscript run_pipeline.R --check                 # consistency check only (step 16)
#   Rscript run_pipeline.R --from 07 --to 09       # run a range
#   Rscript run_pipeline.R --only 11,16            # run selected steps
#   Rscript run_pipeline.R --dry-run               # print the commands instead
#
# 前置条件 / prerequisites:
#   CPAS_DATA_ROOT     data root (default /home/Jingle/data/Project/CPAS)
#   CPAS_PIPELINE_DIR  override for the directory holding the consolidated scripts
#                      (default: system.file("pipeline", package = "CanPAS"))
#   CPAS_DB_PASSWORD   mirror password (only the steps flagged needs_db require it;
#                      when it is unset those steps are refused before anything runs)
#   Steps flagged needs_net fetch GEO/CGGA data; steps flagged needs_db write to
#   the MySQL mirror (06/09/13/14/15/17 and the later repair/upload steps).
#
# 说明: per-cohort arguments are still written inside each step script (historical
#       convention); this entry point owns the order, the pre-flight checks and the
#       log, and does not change any step's behaviour.
# 输出: pipeline/out/pipeline_run_log.csv  (under the data root)
# ----------------------------------------------------------------------------
root <- Sys.getenv("CPAS_DATA_ROOT", unset = "/home/Jingle/data/Project/CPAS")
stopifnot(dir.exists(root))
setwd(root)

# --- where the consolidated scripts live -------------------------------------
pipeline_dir <- Sys.getenv("CPAS_PIPELINE_DIR", unset = "")
if (!nzchar(pipeline_dir)) {
  pipeline_dir <- tryCatch(system.file("pipeline", package = "CanPAS"),
                           error = function(e) "")
}
if (!nzchar(pipeline_dir) || !dir.exists(pipeline_dir)) {
  # running straight from a source checkout: Rscript inst/pipeline/run_pipeline.R
  fa <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  pipeline_dir <- if (length(fa)) dirname(sub("^--file=", "", fa[1])) else getwd()
}
if (!dir.exists(pipeline_dir))
  stop("consolidated pipeline scripts not found (set CPAS_PIPELINE_DIR or install CanPAS)",
       call. = FALSE)

steps <- data.frame(
  id = c("01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "07b",
    "07c",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "90",
    "91",
    "92",
    "93",
    "94",
    "95",
    "96",
    "98",
    "99",
    "100",
    "101",
    "102",
    "103",
    "104",
    "105",
    "106",
    "107",
    "110",
    "111",
    "112",
    "113",
    "batch_integrate",
    "batch_integrate2",
    "demo_meta_lung",
    "demo_tcga_integration",
    "demo_tcga_ondemand",
    "demo_unified_reader",
    "test_cpas_GSE44001",
    "test_cpas_dataset",
    "validate_cpas"),
  script = c("01_parse_gse.R",
    "02_gpl_map.R",
    "03_surv_table.R",
    "04_qc_report.R",
    "05_dataset_plan.R",
    "06_upload_db.R",
    "07_standardize_clinical.R",
    "07b_split_tnm.R",
    "07c_T_usage_table.R",
    "08_verify_normalization.R",
    "09_update_db_surv.R",
    "10_parse_cgga.R",
    "11_endpoint_families.R",
    "12_gpl_map_symbol.R",
    "13_upload_small_cohorts.R",
    "14_split_gse40272_surv.R",
    "15_split_gse40272_expr.R",
    "16_verify_catalog_mirror.R",
    "17_recod_gse86166_status.R",
    "18_log2_transform.R",
    "19_fix_catalog_N.R",
    "20_log2_transform_db.R",
    "21_reupload_log2_tables.R",
    "22_report_log2_impact.R",
    "23_fix_surv_ids_and_endpoints.R",
    "24_make_tables_writable.R",
    "25_fix_endpoint_annotations.R",
    "26_cohort_overlap.R",
    "27_catalog_notes.R",
    "35_add_tcga_cohorts.R",
    "36_screen_geo_candidates.R",
    "37_geo_expansion_screen.R",
    "38_geo_expansion_annotation_check.R",
    "39_build_gse1379_surv.R",
    "40_add_tcga_chol_dlbc.R",
    "41_register_final3_rows.R",
    "42_upload_gpl1223.R",
    "90_build_gse108474_suppl.R",
    "91_complete_gse14520_surv.R",
    "92_build_geo_expansion_expr_pheno.R",
    "93_build_geo_expansion_bespoke.R",
    "94_update_catalog_geo_expansion.R",
    "95_build_suppl_expansion.R",
    "96_build_suppl_expansion.R",
    "98_update_catalog_suppl_expansion.R",
    "99_extend_gpl_db.R",
    "100_build_relaxed_gate.R",
    "101_update_catalog_relaxed_gate.R",
    "102_extend_gpl4133_agilent_name.R",
    "103_build_embl_gpl_maps.R",
    "104_build_embl_cohorts.R",
    "105_update_catalog_embl.R",
    "106_build_embl_step2.R",
    "107_register_embl_step2.R",
    "110_build_gse205209.R",
    "111_register_gse205209.R",
    "112_upload_gpl27956.R",
    "113_sweep_gpl_mirror_divergence.R",
    "batch_integrate.R",
    "batch_integrate2.R",
    "demo_meta_lung.R",
    "demo_tcga_integration.R",
    "demo_tcga_ondemand.R",
    "demo_unified_reader.R",
    "test_cpas_GSE44001.R",
    "test_cpas_dataset.R",
    "validate_cpas.R"),
  group = c("01_ingest_parse.R",
    "02_platform_maps.R",
    "03_survival_tables.R",
    "08_qc_screen_and_verify.R",
    "06_catalog_and_registry.R",
    "07_mirror_upload.R",
    "05_clinical_and_scale.R",
    "05_clinical_and_scale.R",
    "05_clinical_and_scale.R",
    "05_clinical_and_scale.R",
    "07_mirror_upload.R",
    "01_ingest_parse.R",
    "05_clinical_and_scale.R",
    "02_platform_maps.R",
    "07_mirror_upload.R",
    "03_survival_tables.R",
    "03_survival_tables.R",
    "08_qc_screen_and_verify.R",
    "03_survival_tables.R",
    "05_clinical_and_scale.R",
    "06_catalog_and_registry.R",
    "05_clinical_and_scale.R",
    "05_clinical_and_scale.R",
    "05_clinical_and_scale.R",
    "03_survival_tables.R",
    "07_mirror_upload.R",
    "03_survival_tables.R",
    "06_catalog_and_registry.R",
    "06_catalog_and_registry.R",
    "03_survival_tables.R",
    "08_qc_screen_and_verify.R",
    "08_qc_screen_and_verify.R",
    "02_platform_maps.R",
    "03_survival_tables.R",
    "03_survival_tables.R",
    "06_catalog_and_registry.R",
    "07_mirror_upload.R",
    "01_ingest_parse.R",
    "01_ingest_parse.R",
    "01_ingest_parse.R",
    "01_ingest_parse.R",
    "06_catalog_and_registry.R",
    "04_cohort_builds.R",
    "04_cohort_builds.R",
    "06_catalog_and_registry.R",
    "07_mirror_upload.R",
    "04_cohort_builds.R",
    "06_catalog_and_registry.R",
    "02_platform_maps.R",
    "02_platform_maps.R",
    "04_cohort_builds.R",
    "06_catalog_and_registry.R",
    "04_cohort_builds.R",
    "06_catalog_and_registry.R",
    "03_survival_tables.R",
    "06_catalog_and_registry.R",
    "07_mirror_upload.R",
    "08_qc_screen_and_verify.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R",
    "09_analysis_and_figures.R"),
  runner = c("run_01_parse_gse",
    "run_02_gpl_map",
    "run_03_surv_table",
    "run_04_qc_report",
    "run_05_dataset_plan",
    "run_06_upload_db",
    "run_07_standardize_clinical",
    "run_07b_split_tnm",
    "run_07c_T_usage_table",
    "run_08_verify_normalization",
    "run_09_update_db_surv",
    "run_10_parse_cgga",
    "run_11_endpoint_families",
    "run_12_gpl_map_symbol",
    "run_13_upload_small_cohorts",
    "run_14_split_gse40272_surv",
    "run_15_split_gse40272_expr",
    "run_16_verify_catalog_mirror",
    "run_17_recod_gse86166_status",
    "run_18_log2_transform",
    "run_19_fix_catalog_N",
    "run_20_log2_transform_db",
    "run_21_reupload_log2_tables",
    "run_22_report_log2_impact",
    "run_23_fix_surv_ids_and_endpoints",
    "run_24_make_tables_writable",
    "run_25_fix_endpoint_annotations",
    "run_26_cohort_overlap",
    "run_27_catalog_notes",
    "run_35_add_tcga_cohorts",
    "run_36_screen_geo_candidates",
    "run_37_geo_expansion_screen",
    "run_38_geo_expansion_annotation_check",
    "run_39_build_gse1379_surv",
    "run_40_add_tcga_chol_dlbc",
    "run_41_register_final3_rows",
    "run_42_upload_gpl1223",
    "run_90_build_gse108474_suppl",
    "run_91_complete_gse14520_surv",
    "run_92_build_geo_expansion_expr_pheno",
    "run_93_build_geo_expansion_bespoke",
    "run_94_update_catalog_geo_expansion",
    "run_95_build_suppl_expansion",
    "run_96_build_suppl_expansion",
    "run_98_update_catalog_suppl_expansion",
    "run_99_extend_gpl_db",
    "run_100_build_relaxed_gate",
    "run_101_update_catalog_relaxed_gate",
    "run_102_extend_gpl4133_agilent_name",
    "run_103_build_embl_gpl_maps",
    "run_104_build_embl_cohorts",
    "run_105_update_catalog_embl",
    "run_106_build_embl_step2",
    "run_107_register_embl_step2",
    "run_110_build_gse205209",
    "run_111_register_gse205209",
    "run_112_upload_gpl27956",
    "run_113_sweep_gpl_mirror_divergence",
    "run_batch_integrate",
    "run_batch_integrate2",
    "run_demo_meta_lung",
    "run_demo_tcga_integration",
    "run_demo_tcga_ondemand",
    "run_demo_unified_reader",
    "run_test_cpas_GSE44001",
    "run_test_cpas_dataset",
    "run_validate_cpas"),
  what = c("GEO series matrix -> data/raw + data/expr + data/pheno + dataset_info",
    "platform SOFT -> data/processed/gpl/<GPL>.rds probe->ENTREZ map",
    "pheno + specs -> data/processed/surv/<ACC>_surv.rds (endpoints + clinical)",
    "QC table over processed cohorts -> pipeline/out/QC_<date>.csv",
    "master list vs local files vs mirror -> pipeline/out/dataset_plan.csv",
    "local expr/surv/GPL products -> MySQL mirror tables",
    "normalize clinical columns of every local surv table, in place",
    "derive T/N/M columns from a combined stage string, in place",
    "T distribution / usage report -> pipeline/out/clinical_T_distribution_usage.csv",
    "read-only audit of clinical normalization -> report + csv",
    "sync normalized local surv tables into the MySQL mirror",
    "CGGA.zip mRNA-array/seq -> expr + gpl + surv products",
    "endpoint family columns for the catalog (OS/DSS/DFS/PFS/MFS)",
    "platform SOFT with symbols only -> probe->ENTREZ map via bundled ID_map",
    "upload small cohorts (expr + GPL) into the mirror",
    "split the GSE-level surv table per platform and mirror it",
    "split the GSE-level expression matrix per platform and mirror it",
    "catalog <-> mirror consistency check (non-zero exit on error)",
    "recode GSE86166 status 1/2 -> 0/1 (files + mirror)",
    "log2(x+1) scale harmonisation of local expression matrices",
    "recompute the catalog sample-size columns from the mirror",
    "log2(x+1) applied in place to mirror expression tables",
    "re-upload log2-harmonised expression matrices (table rebuild)",
    "report the effect of the log2 harmonisation on HR estimates",
    "repair lost sample ids and broken endpoint columns",
    "rebuild read-only mirror tables as writable ones",
    "fix endpoint annotations and missing clinical data",
    "detect cohorts that share patients; register overlap in the catalog",
    "curated per-cohort notes for the catalog",
    "build + register the 16 additional TCGA cohorts",
    "offline screen of data/raw/*.gz for new GEO candidates",
    "offline screen of pre-fetched headers for gap-cancer candidates",
    "probe->gene annotation availability per screened platform",
    "rebuild GSE1379 survival table from !Sample_description free text",
    "build + register TCGA-CHOL and TCGA-DLBC",
    "append GSE1379 / TCGA-CHOL / TCGA-DLBC rows to the catalog",
    "add the GPL1223 platform table to the mirror",
    "GSE108474 expr/pheno/surv from series matrix + supplementary clinical",
    "complete GSE14520 surv table from the series supplementary file",
    "GEO expansion batch: expr/pheno (+ gpl map) builders",
    "GEO expansion batch: two cohorts needing extra steps",
    "register the GEO expansion cohorts in the catalog",
    "publication-table route cohorts (IMmotion150, ...)",
    "publication-table route cohorts, second round (A5-PCPG, ...)",
    "register the publication-table cohorts in the catalog",
    "append-only extension of mirror GPL tables with new mappings",
    "relaxed-gate cohort build (>=30 usable time+status pairs)",
    "register the relaxed-gate cohorts in the catalog",
    "append Agilent NAME probes to the local GPL4133 map",
    "probe->ENTREZ maps for the two EMBL platforms from platform SOFT",
    "EMBL-EBI (ArrayExpress/BioStudies) cohort builds",
    "register the EMBL-EBI cohorts in the catalog",
    "EMBL-EBI cohorts, step 2 (CEL-only RMA + processed matrices)",
    "register the step-2 EMBL-EBI cohorts in the catalog",
    "GSE205209 (NanoString USC) expr + GPL27956 map + surv",
    "register GSE205209 in the catalog and update excluded.csv",
    "add the GPL27956 platform table to the mirror",
    "read-only sweep of local GPL map vs mirror row counts",
    "integration demo: signatures, per-cancer pooling, KM (uses the mirror)",
    "integration demo, second pass (gastric/ovarian/bladder + MM)",
    "demo: two-stage meta-analysis of lung OS cohorts",
    "demo: TCGA retained-project integration from local rda",
    "demo: TCGA expression on demand from Xena + local survival",
    "demo: materialise the unified reader over 15 TCGA projects",
    "end-to-end test for GSE44001 (cervical, DFS)",
    "end-to-end test for one uploaded dataset (expr -> surv -> COX)",
    "batch validation of every registered cohort (expr -> surv -> univariable COX)"),
  needs_db = c(FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE),
  needs_net = c(TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    FALSE,
    TRUE,
    TRUE,
    TRUE),
  writes_data = c(TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    TRUE),
  stringsAsFactors = FALSE)

args <- commandArgs(trailingOnly = TRUE)
get_arg <- function(flag, default = NULL) {
  i <- match(flag, args)
  if (is.na(i) || i == length(args)) return(default)
  args[i + 1L]
}
if ("--help" %in% args || "-h" %in% args) {
  cat("Usage: Rscript run_pipeline.R [--list] [--check] [--from ID] [--to ID]\n",
      "                                   [--only ID,ID] [--dry-run]\n",
      "\n",
      "Runs the CanPAS curation pipeline from the consolidated scripts under\n",
      "inst/pipeline/.  Without --only/--from/--to every listed step is selected;\n",
      "use --dry-run first, and set CPAS_DATA_ROOT to the project tree.\n")
  quit(status = 0)
}
if ("--list" %in% args) {
  print(steps[, c("id", "script", "group", "what", "needs_db", "needs_net")], row.names = FALSE)
  quit(status = 0)
}

selected <- if ("--check" %in% args) {
  "16"
} else if (!is.null(get_arg("--only"))) {
  trimws(strsplit(get_arg("--only"), ",")[[1]])
} else {
  from <- get_arg("--from", steps$id[1]); to <- get_arg("--to", steps$id[nrow(steps)])
  ids <- steps$id
  ids[seq(match(from, ids), match(to, ids))]
}
unknown <- setdiff(selected, steps$id)
if (length(unknown)) stop("Unknown step id(s): ", paste(unknown, collapse = ", "))
sel <- steps[match(selected, steps$id), , drop = FALSE]
cat(sprintf("Pipeline: %d step(s) selected (%s)\n", nrow(sel), paste(sel$id, collapse = ", ")))

dry <- "--dry-run" %in% args
pw <- Sys.getenv("CPAS_DB_PASSWORD", unset = "")
if (!dry && any(sel$needs_db) && !nzchar(pw))
  stop("These steps need the mirror: ", paste(sel$id[sel$needs_db], collapse = ", "),
       ".\nSet CPAS_DB_PASSWORD (see inst/pipeline/Renviron.example).", call. = FALSE)

log_rows <- list()
for (i in seq_len(nrow(sel))) {
  st <- sel[i, ]
  script <- file.path(pipeline_dir, st$group)
  if (!file.exists(script)) {
    log_rows[[length(log_rows) + 1L]] <- data.frame(step = st$id, script = st$script,
      status = "missing script", seconds = NA_real_, stringsAsFactors = FALSE)
    next
  }
  cat(sprintf("\n=== [%s] %s ===\n", st$id, st$what))
  expr <- sprintf("source(%s); %s()", shQuote(script), st$runner)
  cmd <- sprintf("Rscript -e %s", shQuote(expr))
  if (dry) { cat("  would run:", cmd, "\n"); next }
  t0 <- Sys.time()
  status <- tryCatch({
    code <- system(cmd, ignore.stdout = FALSE, ignore.stderr = FALSE)
    if (identical(code, 0L)) "ok" else paste0("exit ", code)
  }, error = function(e) paste("error:", conditionMessage(e)))
  log_rows[[length(log_rows) + 1L]] <- data.frame(
    step = st$id, script = st$script, status = status,
    seconds = round(as.numeric(difftime(Sys.time(), t0, units = "secs")), 1),
    stringsAsFactors = FALSE)
  if (!identical(status, "ok") && st$id %in% c("16"))
    cat("  check step reported problems (exit code set by the script)\n")
}
if (!dry && length(log_rows)) {
  res <- do.call(rbind, log_rows)
  out <- file.path(root, "pipeline/out/pipeline_run_log.csv")
  dir.create(dirname(out), showWarnings = FALSE, recursive = TRUE)
  if (file.exists(out)) res <- rbind(utils::read.csv(out, stringsAsFactors = FALSE), res)
  utils::write.csv(res, out, row.names = FALSE)
  cat("\n=== pipeline summary ===\n"); print(res, row.names = FALSE)
  cat("log:", out, "\n")
  bad <- res$status[!res$status %in% c("ok")]
  if (length(bad)) quit(status = 1) else quit(status = 0)
}
